# When the workflow succeeds the package will be published to docker hub

name: Publish Docker Images

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: glenndehaan/glenndehaan-website:latest
          build-args: |
            APP_GITHUB_TOKEN=${{ secrets.APP_GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Deploy to Kubernetes
        shell: bash
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          DEPLOY_NAMESPACE: ${{ secrets.DEPLOY_NAMESPACE }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          curl --header "Authorization: Bearer $DEPLOY_TOKEN" "$DEPLOY_URL/deployment/$DEPLOY_NAMESPACE"
